// <auto-generated />
namespace InvestmentManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_attr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_attr));
        
        string IMigrationMetadata.Id
        {
            get { return "201910101123063_user_attr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
